[tool.vulture]
exclude = ["file*.py", "dir/", "convert.py", "train.py", "predict.py", "convert_example.py"]
ignore_decorators = ["@app.route", "@require_*"]
ignore_names = ["visit_*", "do_*"]
make_whitelist = true
min_confidence = 80
paths = ["."]
sort_by_size = true
verbose = true
